import type { Metadata } from 'next';
import './globals.css';
import { MontserratFont } from '@/lib/fonts';
import ToastProvider from '@/components/providers/toast-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${MontserratFont.variable} font-normal antialiased`}>
        <ToastProvider />
        {children}
      </body>
    </html>
  );
}
